strConnection =  "mongodb+srv://luisojeda222:root@cluster0.4yls2sc.mongodb.net/dba_tech_support?retryWrites=true&w=majority"
host = "localhost"
user = "root"
password = "root"
database = "dbatechsupport"